# Site settings
title: S & R Creations
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  Beautiful stained glass decor and jewlery.
baseurl:  ''# the subpath of your site, e.g. /blog/
url: 'sandrcreations.com' # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 6
paginate_path: "/portfolio/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

